// Generated by CoffeeScript 1.10.0
var assert;

assert = chai.assert;

describe('deck', function() {
  var deck, hand;
  deck = null;
  hand = null;
  beforeEach(function() {
    deck = new Deck();
    return hand = deck.dealPlayer();
  });
  return describe('hit', function() {
    return it('should give the last card from the deck', function() {
      var deckLast, handLast;
      assert.strictEqual(deck.length, 50);
      deckLast = deck.last();
      hand.hit();
      handLast = hand.last();
      assert.strictEqual(deckLast, handLast);
      return assert.strictEqual(deck.length, 49);
    });
  });
});
