// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.App = (function(superClass) {
  extend(App, superClass);

  function App() {
    return App.__super__.constructor.apply(this, arguments);
  }

  App.prototype.initialize = function() {
    var deck;
    this.set('deck', deck = new Deck());
    this.set('playerHand', deck.dealPlayer());
    this.set('dealerHand', deck.dealDealer());
    this.get('playerHand').on('all', this.processPlayerEvent, this);
    return this.get('dealerHand').on('all', this.processDealerEvent, this);
  };

  App.prototype.processDealerEvent = function(event, hand) {
    if (event === 'stand') {
      return this.compareScores();
    } else if (event === 'youWin') {
      return this.trigger('youWinApp');
    }
  };

  App.prototype.processPlayerEvent = function(event, hand) {
    if (event === 'stand') {
      this.get('dealerHand').at(0).flip();
      return this.get('dealerHand').dealerPlay();
    } else if (event === 'youWin') {
      return this.trigger('youWinApp');
    } else if (event === 'dealerWins') {
      return this.trigger('dealerWinApp');
    } else if (event === 'blackJackWin') {
      return this.trigger('blackJackWinApp');
    }
  };

  App.prototype.compareScores = function() {
    var dealerScore, playerScore;
    playerScore = this.get('playerHand').scores();
    dealerScore = this.get('dealerHand').scores();
    if (playerScore > dealerScore) {
      return this.trigger('youWinApp');
    } else if (playerScore === dealerScore) {
      return this.trigger('youPushApp');
    } else {
      return this.trigger('dealerWinsApp');

      /*
          @on 'stand', ->
      @.at(0).flip()
      @dealerPlay()
       */
    }
  };

  return App;

})(Backbone.Model);
